name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "30 14 * * *"


jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: bbmt0/waka-readme@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: "░▒▓█"



